### ISSUE TITLE
[FEAT] 컨테이너 페이지 UI 구현

### ISSUE THREAD

**Issue by ChaeYubin** [Web-IDE-Project/front-end#1]
## 🔥 Feature Issue
컨테이너 페이지 UI 구현

## ✅ TODO
- [x] 왼쪽 사이드바 구현
- [x] 왼쪽 사이드바 hide/show 기능 구현
- [x] 오른쪽 컨테이너 뷰어 구현
- [x] 컨테이너 컴포넌트 구현
