### ISSUE TITLE
[FEAT] 컨테이너 실행 기능 구현

### ISSUE THREAD

**Issue by ChaeYubin** [Web-IDE-Project/front-end#32]
## 🔥 Feature Issue
컨테이너 실행 기능 구현

## ✅ TODO
- [x] 컨테이너 실행 시 IDE 페이지로 이동
- [x] 파일트리 정보 받아와서 렌더링
- [x] 선택한 파일을 코드 에디터에 보여주기
