### ISSUE TITLE
[FEAT] 컨테이너 동시 참여자 권한 제어 기능 구현

### ISSUE THREAD

**Issue by ChaeYubin** [Web-IDE-Project/front-end#36]
## 🔥 Feature Issue
컨테이너 동시 참여자별 권한 제어

## ✅ TODO
- [x] 실시간으로 참여한 인원 정보 가져오기(Yorkie 예제 참고)
- [ ] 코드 편집 권한 제어
- [ ] 마이크 권한 제어
