### ISSUE TITLE
[FEAT] 디렉토리/파일 CRUD 기능 구현

### ISSUE THREAD

**Issue by ChaeYubin** [Web-IDE-Project/front-end#38]
## 🔥 Feature Issue
디렉토리/파일 CRUD 기능 구현

## ✅ TODO
- [x] 디렉토리 생성
- [x] 디렉토리 삭제
- [x] 파일 생성
- [x] 파일 삭제
- [x] 디렉토리 이름 수정(예정)
- [x] 파일 이름 수정(예정)

## ➕ 6/13 추가
- [x] API 명세서 변경에 따른 수정
