### ISSUE TITLE
[FEAT] 코드 편집기 페이지 UI 구현

### ISSUE THREAD

**Issue by ChaeYubin** [Web-IDE-Project/front-end#5]
## 🔥 Feature Issue
코드 편집기 페이지 UI 구현

## ✅ TODO
- [x] 상단바 구현(로고, 저장/실행 버튼)
- [x] 왼쪽 탭 및 탭 아이템 구현
- [x] 코드 편집기 띄우기
- [x] 터미널 화면 띄우기
- [x] 파일 탐색기(파일 트리) 띄우기
