### ISSUE TITLE
[FIX] 1차 테스트에서 발생한 이슈 해결

### ISSUE THREAD

**Issue by ChaeYubin** [Web-IDE-Project/front-end#76]
## 🔨 Fix Issue
1차 테스트에서 발생한 이슈 해결

## ✅ TODO
- [ ] 유저 로그인 확인 API 명세서 다시 확인 후 수정
- [ ] 컨테이너 생성 시 새로고침해야 생성한 컨테이너가 보이는 문제 해결
- [ ] 엔트리 관련 기본 계층구조 데이터 타입 수정(최상위 디렉토리 - 기본 템플릿 파일)
- [ ] 파일 저장 API 주소 확인
- [ ] yorkie 내용 state에 저장하기
- [ ] 파일/디렉토리 생성 시 모달에서 중복되는 부분 수정
- [ ] 파일 실행 API 명세서 확인 후 수정
- [ ] 파일 실행 시 cmd 창에 나오는 결과 개행 문자 수정
- [ ] 컨테이너 페이지에서 왼쪽 사이드 바 위치 고정하기
- [ ] TreeView 기본 확장 폴더 및 기본 선택 파일 id 동적으로 수정
- [ ] 파일 삭제 후 TreeView에서 발생하는 오류 해결
- [ ] Navbar 파일 저장 toast 발생 위치 수정
