### ISSUE TITLE
[FEAT] 코드 편집기 기능 구현

### ISSUE THREAD

**Issue by ChaeYubin** [Web-IDE-Project/front-end#8]
## 🔥 Feature Issue
코드 편집기 기능 구현

## ✅ TODO
- [x] 파일 내 코드 편집
- [x] 파일 내 코드 저장
- [x] 파일 내 코드 실행

## ➕ 6/13 추가
- [x] API 명세서 변경에 따른 수정
